name: linting, testing and building

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Build prod project
              run: npm run build:prod
            - name: linting TS
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit tests
              run: npm run test:unit
            - name: build storybook
              run: npm run storybook:build
            - name: Pull Chrome Docker image
              run: docker pull yukinying/chrome-headless-browser:90.0.4408.0
            - name: screenshot tests
              run: npm run test:ui:ci
